import type {
  M365User, UserGroup, Asset, AssetCategory,
  OnboardingWorkflow, OffboardingWorkflow,
  UnifiSite, UnifiDevice,
  ActivityItem, DashboardStats, SystemStatus,
  M365License, M365App, IntuneDevice, DashboardAdmin
} from '@/types';

// Mock M365 Users
export const mockM365Users: M365User[] = [
  {
    id: '1',
    userPrincipalName: 'john.doe@company.com',
    displayName: 'John Doe',
    givenName: 'John',
    surname: 'Doe',
    email: 'john.doe@company.com',
    department: 'Engineering',
    jobTitle: 'Senior Developer',
    officeLocation: 'New York',
    accountEnabled: true,
    createdDateTime: '2023-01-15T00:00:00Z',
    lastSignInDateTime: '2024-01-20T08:30:00Z',
    mfaEnabled: true,
  },
  {
    id: '2',
    userPrincipalName: 'jane.smith@company.com',
    displayName: 'Jane Smith',
    givenName: 'Jane',
    surname: 'Smith',
    email: 'jane.smith@company.com',
    department: 'Marketing',
    jobTitle: 'Marketing Manager',
    officeLocation: 'London',
    accountEnabled: true,
    createdDateTime: '2023-03-10T00:00:00Z',
    lastSignInDateTime: '2024-01-19T16:45:00Z',
    mfaEnabled: true,
  },
  {
    id: '3',
    userPrincipalName: 'mike.johnson@company.com',
    displayName: 'Mike Johnson',
    givenName: 'Mike',
    surname: 'Johnson',
    email: 'mike.johnson@company.com',
    department: 'Sales',
    jobTitle: 'Sales Representative',
    officeLocation: 'New York',
    accountEnabled: true,
    createdDateTime: '2023-06-01T00:00:00Z',
    lastSignInDateTime: '2024-01-20T09:15:00Z',
    mfaEnabled: false,
  },
  {
    id: '4',
    userPrincipalName: 'sarah.williams@company.com',
    displayName: 'Sarah Williams',
    givenName: 'Sarah',
    surname: 'Williams',
    email: 'sarah.williams@company.com',
    department: 'HR',
    jobTitle: 'HR Specialist',
    officeLocation: 'London',
    accountEnabled: true,
    createdDateTime: '2023-02-20T00:00:00Z',
    lastSignInDateTime: '2024-01-18T14:20:00Z',
    mfaEnabled: true,
  },
  {
    id: '5',
    userPrincipalName: 'david.brown@company.com',
    displayName: 'David Brown',
    givenName: 'David',
    surname: 'Brown',
    email: 'david.brown@company.com',
    department: 'IT',
    jobTitle: 'IT Administrator',
    officeLocation: 'New York',
    accountEnabled: true,
    createdDateTime: '2022-11-05T00:00:00Z',
    lastSignInDateTime: '2024-01-20T07:45:00Z',
    mfaEnabled: true,
  },
  {
    id: '6',
    userPrincipalName: 'emily.davis@company.com',
    displayName: 'Emily Davis',
    givenName: 'Emily',
    surname: 'Davis',
    email: 'emily.davis@company.com',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    officeLocation: 'Singapore',
    accountEnabled: false,
    createdDateTime: '2023-08-12T00:00:00Z',
    lastSignInDateTime: '2023-12-15T10:30:00Z',
    mfaEnabled: true,
  },
  {
    id: '7',
    userPrincipalName: 'robert.miller@company.com',
    displayName: 'Robert Miller',
    givenName: 'Robert',
    surname: 'Miller',
    email: 'robert.miller@company.com',
    department: 'Engineering',
    jobTitle: 'DevOps Engineer',
    officeLocation: 'Singapore',
    accountEnabled: true,
    createdDateTime: '2023-04-18T00:00:00Z',
    lastSignInDateTime: '2024-01-19T11:00:00Z',
    mfaEnabled: true,
  },
];

// Mock User Groups
export const mockUserGroups: UserGroup[] = [
  {
    id: '1',
    displayName: 'Engineering Team',
    description: 'All engineering department members',
    groupType: 'Security',
    memberCount: 45,
  },
  {
    id: '2',
    displayName: 'Marketing Team',
    description: 'Marketing department members',
    groupType: 'Security',
    memberCount: 23,
  },
  {
    id: '3',
    displayName: 'Sales Team',
    description: 'Sales department members',
    groupType: 'Security',
    memberCount: 38,
  },
  {
    id: '4',
    displayName: 'IT Administrators',
    description: 'IT department administrators',
    groupType: 'Security',
    memberCount: 12,
  },
  {
    id: '5',
    displayName: 'All Employees',
    description: 'All company employees',
    groupType: 'Distribution',
    memberCount: 245,
  },
  {
    id: '6',
    displayName: 'Remote Workers',
    description: 'Employees working remotely',
    groupType: 'Microsoft365',
    memberCount: 89,
  },
  {
    id: '7',
    displayName: 'Project Alpha',
    description: 'Project Alpha team members',
    groupType: 'Microsoft365',
    memberCount: 15,
  },
  {
    id: '8',
    displayName: 'Executives',
    description: 'Executive leadership team',
    groupType: 'Security',
    memberCount: 8,
  },
];

// Mock Assets
export const mockAssets: Asset[] = [
  {
    id: '1',
    assetTag: 'LAPTOP-001',
    name: 'Dell Latitude 7420',
    category: 'Laptops',
    manufacturer: 'Dell',
    model: 'Latitude 7420',
    serialNumber: 'ABC123456',
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    status: 'assigned',
    assignedTo: '1',
    assignedToName: 'John Doe',
    location: 'New York',
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2023-01-15T00:00:00Z',
  },
  {
    id: '2',
    assetTag: 'LAPTOP-002',
    name: 'MacBook Pro 14"',
    category: 'Laptops',
    manufacturer: 'Apple',
    model: 'MacBook Pro 14" M2',
    serialNumber: 'C02XYZ789',
    purchaseDate: '2023-02-20',
    warrantyExpiry: '2026-02-20',
    status: 'assigned',
    assignedTo: '2',
    assignedToName: 'Jane Smith',
    location: 'London',
    createdAt: '2023-02-20T00:00:00Z',
    updatedAt: '2023-02-20T00:00:00Z',
  },
  {
    id: '3',
    assetTag: 'DESKTOP-002',
    name: 'Lenovo ThinkCentre M90',
    category: 'Desktops',
    manufacturer: 'Lenovo',
    model: 'ThinkCentre M90',
    serialNumber: 'LNV987654',
    purchaseDate: '2022-11-10',
    warrantyExpiry: '2025-11-10',
    status: 'available',
    location: 'Singapore',
    createdAt: '2022-11-10T00:00:00Z',
    updatedAt: '2023-08-15T00:00:00Z',
  },
  {
    id: '4',
    assetTag: 'DESKTOP-001',
    name: 'HP EliteDesk 800',
    category: 'Desktops',
    manufacturer: 'HP',
    model: 'EliteDesk 800 G9',
    serialNumber: '5CG1234ABC',
    purchaseDate: '2023-03-01',
    warrantyExpiry: '2026-03-01',
    status: 'available',
    location: 'New York',
    createdAt: '2023-03-01T00:00:00Z',
    updatedAt: '2023-03-01T00:00:00Z',
  },
  {
    id: '5',
    assetTag: 'MONITOR-001',
    name: 'Dell UltraSharp 27"',
    category: 'Peripherals',
    manufacturer: 'Dell',
    model: 'U2723QE',
    serialNumber: 'CN012345',
    purchaseDate: '2023-04-10',
    warrantyExpiry: '2026-04-10',
    status: 'assigned',
    assignedTo: '3',
    assignedToName: 'Mike Johnson',
    location: 'New York',
    createdAt: '2023-04-10T00:00:00Z',
    updatedAt: '2023-06-01T00:00:00Z',
  },
  {
    id: '6',
    assetTag: 'SWITCH-001',
    name: 'UniFi Switch Pro 24',
    category: 'Network Equipment',
    manufacturer: 'Ubiquiti',
    model: 'USW-Pro-24',
    serialNumber: '18A9ABCDEF',
    purchaseDate: '2022-12-01',
    warrantyExpiry: '2025-12-01',
    status: 'assigned',
    location: 'New York',
    notes: 'Main office network switch',
    createdAt: '2022-12-01T00:00:00Z',
    updatedAt: '2022-12-01T00:00:00Z',
  },
  {
    id: '7',
    assetTag: 'LAPTOP-003',
    name: 'MacBook Air M2',
    category: 'Laptops',
    manufacturer: 'Apple',
    model: 'MacBook Air 13" M2',
    serialNumber: 'C02ABC456',
    purchaseDate: '2023-05-15',
    warrantyExpiry: '2026-05-15',
    status: 'maintenance',
    location: 'London',
    notes: 'Screen replacement in progress',
    createdAt: '2023-05-15T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '8',
    assetTag: 'LICENSE-001',
    name: 'Microsoft 365 E5',
    category: 'Software Licenses',
    manufacturer: 'Microsoft',
    model: 'M365 E5',
    purchaseDate: '2023-01-01',
    warrantyExpiry: '2024-12-31',
    status: 'assigned',
    assignedTo: '5',
    assignedToName: 'David Brown',
    location: 'Cloud',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
];

// Mock Asset Categories
export const mockAssetCategories: AssetCategory[] = [
  { id: '1', name: 'Laptops', description: 'Portable computers', icon: 'Laptop', count: 3 },
  { id: '2', name: 'Desktops', description: 'Desktop computers', icon: 'Monitor', count: 2 },
  { id: '3', name: 'Peripherals', description: 'Monitors, keyboards, mice', icon: 'Mouse', count: 1 },
  { id: '4', name: 'Network Equipment', description: 'Switches, routers, access points', icon: 'Network', count: 1 },
  { id: '5', name: 'Software Licenses', description: 'Software licenses and subscriptions', icon: 'Key', count: 1 },
];

// Mock M365 Licenses
export const mockM365Licenses: M365License[] = [
  {
    id: '1',
    skuId: 'c7df2760-2c81-4ef7-b578-5b5392b571df',
    name: 'Microsoft 365 E5',
    description: 'Full suite with advanced security, compliance, and analytics',
    availableUnits: 50,
    consumedUnits: 32,
    category: 'Microsoft365'
  },
  {
    id: '2',
    skuId: '6fd2c87f-b296-42f0-b197-1e91e994b900',
    name: 'Microsoft 365 E3',
    description: 'Core productivity and security tools',
    availableUnits: 100,
    consumedUnits: 78,
    category: 'Microsoft365'
  },
  {
    id: '3',
    skuId: 'f245ecc8-75af-4f8e-b61f-27d8114de5f3',
    name: 'Microsoft 365 Business Premium',
    description: 'Complete solution for small to medium businesses',
    availableUnits: 25,
    consumedUnits: 18,
    category: 'Microsoft365'
  },
  {
    id: '4',
    skuId: '18181a46-0d4e-45cd-891e-60aabd171b4e',
    name: 'Office 365 E1',
    description: 'Web-based Office apps and email',
    availableUnits: 200,
    consumedUnits: 145,
    category: 'Office365'
  },
  {
    id: '5',
    skuId: '6634e0ce-1a9f-428c-a498-f84ec7b8aa2e',
    name: 'Power BI Pro',
    description: 'Business analytics and data visualization',
    availableUnits: 30,
    consumedUnits: 22,
    category: 'PowerBI'
  },
  {
    id: '6',
    skuId: 'efccb6f7-5641-4e0e-bd10-b4976e1bf68e',
    name: 'Enterprise Mobility + Security E5',
    description: 'Advanced identity and information protection',
    availableUnits: 50,
    consumedUnits: 35,
    category: 'EMS'
  },
];

// Mock M365 Apps
export const mockM365Apps: M365App[] = [
  { id: '1', name: 'Microsoft Teams', category: 'Collaboration', icon: 'MessageSquare', enabled: true },
  { id: '2', name: 'SharePoint', category: 'Collaboration', icon: 'Share2', enabled: true },
  { id: '3', name: 'OneDrive', category: 'Collaboration', icon: 'Cloud', enabled: true },
  { id: '4', name: 'Exchange Online', category: 'Collaboration', icon: 'Mail', enabled: true },
  { id: '5', name: 'Word', category: 'Office', icon: 'FileText', enabled: true },
  { id: '6', name: 'Excel', category: 'Office', icon: 'Table', enabled: true },
  { id: '7', name: 'PowerPoint', category: 'Office', icon: 'Presentation', enabled: true },
  { id: '8', name: 'OneNote', category: 'Office', icon: 'BookOpen', enabled: true },
  { id: '9', name: 'Power BI', category: 'Analytics', icon: 'BarChart3', enabled: false },
  { id: '10', name: 'Planner', category: 'Collaboration', icon: 'Calendar', enabled: true },
  { id: '11', name: 'Yammer', category: 'Collaboration', icon: 'Users', enabled: false },
  { id: '12', name: 'Defender', category: 'Security', icon: 'Shield', enabled: true },
];

// Mock Intune Devices
export const mockIntuneDevices: IntuneDevice[] = [
  {
    id: '1',
    deviceName: 'LAPTOP-WIN-001',
    deviceType: 'Windows',
    model: 'Dell Latitude 7420',
    osVersion: 'Windows 11 Pro 22H2',
    serialNumber: 'ABC123456',
    enrollmentDate: '2023-06-15',
    lastSync: '2024-01-20T10:30:00Z',
    complianceState: 'Compliant',
    primaryUser: null,
    status: 'available'
  },
  {
    id: '2',
    deviceName: 'LAPTOP-MAC-001',
    deviceType: 'macOS',
    model: 'MacBook Pro 14"',
    osVersion: 'macOS 14.2',
    serialNumber: 'C02XYZ789',
    enrollmentDate: '2023-07-20',
    lastSync: '2024-01-20T09:15:00Z',
    complianceState: 'Compliant',
    primaryUser: '2',
    primaryUserName: 'Jane Smith',
    status: 'assigned'
  },
  {
    id: '3',
    deviceName: 'IPHONE-001',
    deviceType: 'iOS',
    model: 'iPhone 14 Pro',
    osVersion: 'iOS 17.2',
    serialNumber: 'DNPQR12345',
    enrollmentDate: '2023-08-10',
    lastSync: '2024-01-20T11:45:00Z',
    complianceState: 'Compliant',
    primaryUser: '1',
    primaryUserName: 'John Doe',
    status: 'assigned'
  },
  {
    id: '4',
    deviceName: 'LAPTOP-WIN-002',
    deviceType: 'Windows',
    model: 'HP EliteBook 840',
    osVersion: 'Windows 11 Pro 23H2',
    serialNumber: '5CG9876543',
    enrollmentDate: '2023-09-05',
    lastSync: '2024-01-19T16:20:00Z',
    complianceState: 'Compliant',
    primaryUser: null,
    status: 'available'
  },
  {
    id: '5',
    deviceName: 'ANDROID-TAB-001',
    deviceType: 'Android',
    model: 'Samsung Galaxy Tab S8',
    osVersion: 'Android 13',
    serialNumber: 'RZ8W12345AB',
    enrollmentDate: '2023-10-12',
    lastSync: '2024-01-20T08:00:00Z',
    complianceState: 'NonCompliant',
    primaryUser: '3',
    primaryUserName: 'Mike Johnson',
    status: 'assigned'
  },
  {
    id: '6',
    deviceName: 'LAPTOP-MAC-002',
    deviceType: 'macOS',
    model: 'MacBook Air M2',
    osVersion: 'macOS 14.1',
    serialNumber: 'C02ABC456',
    enrollmentDate: '2023-11-18',
    lastSync: '2024-01-18T14:30:00Z',
    complianceState: 'InGracePeriod',
    primaryUser: null,
    status: 'available'
  },
  {
    id: '7',
    deviceName: 'LAPTOP-WIN-003',
    deviceType: 'Windows',
    model: 'Lenovo ThinkPad X1',
    osVersion: 'Windows 11 Pro 22H2',
    serialNumber: 'LNV456789',
    enrollmentDate: '2023-12-01',
    lastSync: '2024-01-20T07:45:00Z',
    complianceState: 'Compliant',
    primaryUser: '5',
    primaryUserName: 'David Brown',
    status: 'assigned'
  },
];

// Mock Onboarding Workflows
export const mockOnboardingWorkflows: OnboardingWorkflow[] = [
  {
    id: '1',
    employeeName: 'Alice Cooper',
    employeeEmail: 'alice.cooper@company.com',
    startDate: '2024-02-01',
    department: 'Engineering',
    jobTitle: 'Software Engineer',
    managerId: '1',
    managerName: 'John Doe',
    location: 'New York',
    status: 'in_progress',
    createdBy: 'admin',
    createdAt: '2024-01-15T00:00:00Z',
    progress: 60,
  },
  {
    id: '2',
    employeeName: 'Bob Wilson',
    employeeEmail: 'bob.wilson@company.com',
    startDate: '2024-02-05',
    department: 'Sales',
    jobTitle: 'Sales Executive',
    managerId: '3',
    managerName: 'Mike Johnson',
    location: 'London',
    status: 'pending',
    createdBy: 'admin',
    createdAt: '2024-01-18T00:00:00Z',
    progress: 0,
  },
];

// Mock Offboarding Workflows
export const mockOffboardingWorkflows: OffboardingWorkflow[] = [
  {
    id: '1',
    userId: '6',
    employeeName: 'Emily Davis',
    employeeEmail: 'emily.davis@company.com',
    departureDate: '2024-01-31',
    reason: 'Resignation',
    disableAccount: true,
    revokeSessions: true,
    removeMfa: true,
    removeGroups: true,
    forwardEmail: 'sarah.williams@company.com',
    archiveData: true,
    status: 'in_progress',
    createdBy: 'admin',
    createdAt: '2024-01-10T00:00:00Z',
    progress: 75,
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalUsers: 245,
  activeUsers: 238,
  totalAssets: 1087,
  assignedAssets: 874,
  pendingOnboarding: 5,
  pendingOffboarding: 2,
  usersTrend: 12.5,
  assetsTrend: 8.3,
};

// Mock Activity Items
export const mockActivityItems: ActivityItem[] = [
  {
    id: '1',
    timestamp: '2024-01-20T10:30:00Z',
    user: 'admin',
    action: 'created',
    target: 'Alice Cooper',
    status: 'success',
  },
  {
    id: '2',
    timestamp: '2024-01-20T09:15:00Z',
    user: 'admin',
    action: 'assigned',
    target: 'Dell Latitude 7420',
    status: 'success',
  },
  {
    id: '3',
    timestamp: '2024-01-19T16:45:00Z',
    user: 'admin',
    action: 'assigned',
    target: 'Microsoft 365 E5',
    status: 'success',
  },
  {
    id: '4',
    timestamp: '2024-01-19T14:20:00Z',
    user: 'admin',
    action: 'offboarded',
    target: 'Emily Davis',
    status: 'success',
  },
];

// Mock System Status
export const mockSystemStatus: SystemStatus = {
  microsoft: {
    overall: 'operational',
    lastSync: '2024-01-20T12:00:00Z',
    services: [
      { name: 'Exchange Online', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'SharePoint Online', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'Teams', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'OneDrive', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'Entra ID', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'Intune', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
    ]
  },
  unifi: {
    overall: 'operational',
    lastSync: '2024-01-20T12:00:00Z',
    services: [
      { name: 'New York HQ', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'London Branch', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'Singapore Hub', status: 'operational', lastUpdated: '2024-01-20T12:00:00Z' },
      { name: 'Remote Operations', status: 'degraded', lastUpdated: '2024-01-20T12:00:00Z' },
    ]
  },
};

// Mock Department Distribution Data
export const mockDepartmentData = [
  { name: 'Engineering', value: 85, color: '#3b82f6' },
  { name: 'Sales', value: 62, color: '#10b981' },
  { name: 'Marketing', value: 38, color: '#f59e0b' },
  { name: 'IT', value: 24, color: '#8b5cf6' },
  { name: 'Finance', value: 18, color: '#ec4899' },
  { name: 'Operations', value: 18, color: '#06b6d4' },
];

export const mockAssetStatusData = [
  { name: 'Assigned', value: 874 },
  { name: 'Available', value: 45 },
  { name: 'Maintenance', value: 12 },
  { name: 'Retired', value: 156 },
];

export const mockLifecycleData = [
  { name: 'Jan', onboarding: 4, offboarding: 2 },
  { name: 'Feb', onboarding: 7, offboarding: 3 },
  { name: 'Mar', onboarding: 5, offboarding: 4 },
  { name: 'Apr', onboarding: 9, offboarding: 1 },
  { name: 'May', onboarding: 3, offboarding: 5 },
  { name: 'Jun', onboarding: 6, offboarding: 2 },
];

// Mock Dashboard Admins
export const mockDashboardAdmins: DashboardAdmin[] = [
  {
    id: 'admin-1',
    username: 'admin',
    email: 'admin@company.com',
    role: 'it_admin',
    permissions: {
      dashboard: true,
      users: true,
      assets: true,
      software: true,
      onboarding: true,
      offboarding: true,
      network: true,
      sites: true,
      proxmox: true,
      patchManagement: true,
      reports: true,
      auditLogs: true,
      settings: true,
    },
    status: 'active',
    lastLogin: '2024-01-20T14:30:00Z',
    createdAt: '2023-06-15T10:00:00Z',
    createdBy: 'system',
  },
  {
    id: 'admin-2',
    username: 'john.smith',
    email: 'john.smith@company.com',
    role: 'it_user',
    permissions: {
      dashboard: true,
      users: true,
      assets: true,
      software: true,
      onboarding: true,
      offboarding: true,
      network: false,
      sites: false,
      proxmox: false,
      patchManagement: false,
      reports: true,
      auditLogs: false,
      settings: false,
    },
    status: 'active',
    lastLogin: '2024-01-20T11:15:00Z',
    createdAt: '2023-08-22T09:30:00Z',
    createdBy: 'admin',
  },
  {
    id: 'admin-3',
    username: 'jane.doe',
    email: 'jane.doe@company.com',
    role: 'it_user',
    permissions: {
      dashboard: true,
      users: false,
      assets: true,
      software: true,
      onboarding: false,
      offboarding: false,
      network: true,
      sites: true,
      proxmox: true,
      patchManagement: true,
      reports: true,
      auditLogs: false,
      settings: false,
    },
    status: 'active',
    lastLogin: '2024-01-19T16:45:00Z',
    createdAt: '2023-09-10T14:20:00Z',
    createdBy: 'admin',
  },
  {
    id: 'admin-4',
    username: 'mike.wilson',
    email: 'mike.wilson@company.com',
    role: 'viewer',
    permissions: {
      dashboard: true,
      users: false,
      assets: false,
      software: false,
      onboarding: false,
      offboarding: false,
      network: false,
      sites: false,
      proxmox: false,
      patchManagement: false,
      reports: true,
      auditLogs: false,
      settings: false,
    },
    status: 'active',
    lastLogin: '2024-01-18T10:20:00Z',
    createdAt: '2023-11-05T11:00:00Z',
    createdBy: 'admin',
  },
  {
    id: 'admin-5',
    username: 'sarah.brown',
    email: 'sarah.brown@company.com',
    role: 'it_user',
    permissions: {
      dashboard: true,
      users: true,
      assets: true,
      software: false,
      onboarding: true,
      offboarding: true,
      network: false,
      sites: false,
      proxmox: false,
      patchManagement: false,
      reports: false,
      auditLogs: false,
      settings: false,
    },
    status: 'inactive',
    lastLogin: '2023-12-10T15:30:00Z',
    createdAt: '2023-07-18T13:45:00Z',
    createdBy: 'admin',
  },
];
